apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qxx1m8lom-nodejs 
  janus-idp.io/tekton: qxx1m8lom-nodejs
  backstage.io/kubernetes-id: qxx1m8lom-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qxx1m8lom-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml