apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qxx1m8lom-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qxx1m8lom-nodejs 
  name: qxx1m8lom-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qxx1m8lom-nodejs 
